//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace ASTROMARINES.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    var temp = new ResourceManager("ASTROMARINES.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\characters\\boss.png.
        /// </summary>
        internal static string Boss {
            get {
                return ResourceManager.GetString("Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\music\\bossbg.ogg.
        /// </summary>
        internal static string BossBGMusic {
            get {
                return ResourceManager.GetString("BossBGMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\characters\\bossmaincannon.png.
        /// </summary>
        internal static string BossMainCannon {
            get {
                return ResourceManager.GetString("BossMainCannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\sfx\\boss1SpecialSFX.ogg.
        /// </summary>
        internal static string BossSpecialSFX {
            get {
                return ResourceManager.GetString("BossSpecialSFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\sfx\\warp.ogg.
        /// </summary>
        internal static string BossWarpSound {
            get {
                return ResourceManager.GetString("BossWarpSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\images\\credits.png.
        /// </summary>
        internal static string CreditsBG {
            get {
                return ResourceManager.GetString("CreditsBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\characters\\powerup.png.
        /// </summary>
        internal static string Enemy1 {
            get {
                return ResourceManager.GetString("Enemy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\characters\\enemy2.png.
        /// </summary>
        internal static string Enemy2 {
            get {
                return ResourceManager.GetString("Enemy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\characters\\enemy3.png.
        /// </summary>
        internal static string Enemy3 {
            get {
                return ResourceManager.GetString("Enemy3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\characters\\enemy4.png.
        /// </summary>
        internal static string Enemy4 {
            get {
                return ResourceManager.GetString("Enemy4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\sfx\\explosion.ogg.
        /// </summary>
        internal static string ExplosionSound {
            get {
                return ResourceManager.GetString("ExplosionSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\sfx\\explosion.png.
        /// </summary>
        internal static string ExplosionSprite {
            get {
                return ResourceManager.GetString("ExplosionSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\fonts\\digitalClock.ttf.
        /// </summary>
        internal static string FontDigitalClock {
            get {
                return ResourceManager.GetString("FontDigitalClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\fonts\\digitalFont.ttf.
        /// </summary>
        internal static string FontDigitalFont {
            get {
                return ResourceManager.GetString("FontDigitalFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\fonts\\mainGameFont.ttf.
        /// </summary>
        internal static string FontMainGameFont {
            get {
                return ResourceManager.GetString("FontMainGameFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\images\\howToPlay.png.
        /// </summary>
        internal static string HowToPlayBG {
            get {
                return ResourceManager.GetString("HowToPlayBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\images\\levelbg.png.
        /// </summary>
        internal static string LevelBG {
            get {
                return ResourceManager.GetString("LevelBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\music\\levelbg.ogg.
        /// </summary>
        internal static string LevelBGMusic {
            get {
                return ResourceManager.GetString("LevelBGMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\images\\menu.png.
        /// </summary>
        internal static string MenuBG {
            get {
                return ResourceManager.GetString("MenuBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\music\\menubg.ogg.
        /// </summary>
        internal static string MenuBGMusic {
            get {
                return ResourceManager.GetString("MenuBGMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\characters\\player.png.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\images\\plot.png.
        /// </summary>
        internal static string PlotBG {
            get {
                return ResourceManager.GetString("PlotBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets\\images\\title.png.
        /// </summary>
        internal static string TitleBG {
            get {
                return ResourceManager.GetString("TitleBG", resourceCulture);
            }
        }
    }
}
